// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCccwFMER645nsgH1-0G31nSHL2HFDZg8Y',
    appId: '1:931766122770:web:6f94dfcc2ab2f02b3b9bcb',
    messagingSenderId: '931766122770',
    projectId: 'btown-55cdc',
    authDomain: 'btown-55cdc.firebaseapp.com',
    storageBucket: 'btown-55cdc.appspot.com',
    measurementId: 'G-PVFKCMK15R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClMmz4Tv6MbmBHnnF7pLK3Y4KYnqb56y0',
    appId: '1:931766122770:android:e57bc267c8029d8f3b9bcb',
    messagingSenderId: '931766122770',
    projectId: 'btown-55cdc',
    storageBucket: 'btown-55cdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA25SlPUK5t7zcc275_55r19-imX56ZrqY',
    appId: '1:931766122770:ios:60135f0f180eecf73b9bcb',
    messagingSenderId: '931766122770',
    projectId: 'btown-55cdc',
    storageBucket: 'btown-55cdc.appspot.com',
    iosBundleId: 'com.example.chatAppAdmin',
  );
}
